import "~/styles/globals.css";

import type { Metadata } from "next";

import ClientProviders from "@/components/layout/ClientProviders";
import EmotionCacheProvider from "@/lib/emotion-cache";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<EmotionCacheProvider>
					<ClientProviders>{children}</ClientProviders>
				</EmotionCacheProvider>
			</body>
		</html>
	);
}
